# Generated by Django 6.0.4 on 2026-04-19 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sintoma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=255, verbose_name="Descripción del síntoma"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Síntoma",
                "verbose_name_plural": "Síntomas",
                "ordering": ["subsistema", "descripcion"],
            },
        ),
        migrations.CreateModel(
            name="Subsistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Subsistema",
                "verbose_name_plural": "Subsistemas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Ascensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        help_text="Código interno o número de contrato.",
                        max_length=50,
                        unique=True,
                        verbose_name="Identificador",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=255, verbose_name="Dirección"),
                ),
                (
                    "fabricante",
                    models.CharField(max_length=100, verbose_name="Fabricante"),
                ),
                (
                    "modelo",
                    models.CharField(blank=True, max_length=100, verbose_name="Modelo"),
                ),
                (
                    "tipo_maniobra",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo de maniobra"
                    ),
                ),
                (
                    "tipo_ascensor",
                    models.CharField(
                        choices=[
                            ("electrico_traccion", "Eléctrico de tracción"),
                            ("hidraulico", "Hidráulico"),
                            ("sin_cuarto_maquinas", "Sin cuarto de máquinas (MRL)"),
                            ("montacargas", "Montacargas"),
                            ("otro", "Otro"),
                        ],
                        default="electrico_traccion",
                        max_length=30,
                        verbose_name="Tipo de ascensor",
                    ),
                ),
                (
                    "anio_instalacion",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Año de instalación"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "tecnicos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ascensores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Técnicos asignados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ascensor",
                "verbose_name_plural": "Ascensores",
                "ordering": ["direccion"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("tecnico_campo", "Técnico de Campo"),
                            ("tecnico_senior", "Técnico Sénior"),
                        ],
                        default="tecnico_campo",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de usuario",
                "verbose_name_plural": "Perfiles de usuario",
            },
        ),
        migrations.CreateModel(
            name="Intervencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora de inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha y hora de fin"
                    ),
                ),
                (
                    "diagnostico_generado",
                    models.TextField(
                        blank=True,
                        help_text="JSON con la lista de causas probables devuelta por el motor.",
                        verbose_name="Diagnóstico generado",
                    ),
                ),
                (
                    "causa_confirmada",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Causa confirmada"
                    ),
                ),
                (
                    "accion_correctiva",
                    models.TextField(
                        blank=True, verbose_name="Acción correctiva aplicada"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("resuelto", "Resuelto"),
                            ("no_resuelto", "No resuelto"),
                            ("derivado_senior", "Derivado a Técnico Sénior"),
                            ("no_diagnosticado", "Causa no determinada"),
                        ],
                        default="resuelto",
                        max_length=20,
                        verbose_name="Resultado",
                    ),
                ),
                (
                    "ascensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intervenciones",
                        to="diagnostico.ascensor",
                        verbose_name="Ascensor",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intervenciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Técnico",
                    ),
                ),
                (
                    "sintomas_registrados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="intervenciones",
                        to="diagnostico.sintoma",
                        verbose_name="Síntomas registrados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervención",
                "verbose_name_plural": "Intervenciones",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.AddField(
            model_name="sintoma",
            name="subsistema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sintomas",
                to="diagnostico.subsistema",
                verbose_name="Subsistema",
            ),
        ),
        migrations.CreateModel(
            name="Regla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="Nombre de la regla"),
                ),
                (
                    "causa_probable",
                    models.CharField(max_length=255, verbose_name="Causa probable"),
                ),
                (
                    "pasos_comprobacion",
                    models.TextField(
                        help_text="Un paso por línea. Se mostrarán como lista numerada al técnico.",
                        verbose_name="Pasos de comprobación",
                    ),
                ),
                (
                    "criticidad",
                    models.CharField(
                        choices=[
                            ("critico", "Crítico"),
                            ("urgente", "Urgente"),
                            ("diferible", "Diferible"),
                        ],
                        default="urgente",
                        max_length=10,
                        verbose_name="Criticidad",
                    ),
                ),
                (
                    "peso_base",
                    models.FloatField(
                        default=1.0,
                        help_text="Probabilidad base de esta causa (0.1 – 10.0).",
                        verbose_name="Peso base",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "sintomas_requeridos",
                    models.ManyToManyField(
                        help_text="La regla se activa cuando TODOS estos síntomas están presentes.",
                        related_name="reglas",
                        to="diagnostico.sintoma",
                        verbose_name="Síntomas requeridos",
                    ),
                ),
                (
                    "subsistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas",
                        to="diagnostico.subsistema",
                        verbose_name="Subsistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de diagnóstico",
                "verbose_name_plural": "Reglas de diagnóstico",
                "ordering": ["subsistema", "nombre"],
            },
        ),
    ]
